port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
ipv6: false
udp: true
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /usr/share/metacubexd
unified-delay: true
secret: ""
experimental:
  ignore-resolve-fail: true
cfw-latency-timeout: 8000
cfw-latency-url: "http://YouTube.com/generate_204"
cfw-conn-break-strategy: true
dns:
  enable: true
  listen: "127.0.0.1:7874"
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver: [127.0.0.1:6253]
  fallback: ["119.29.29.29"]
