log:
  level: info
  file: "/var/log/mosdns.log"

# API 入口设置
api:
  http: "0.0.0.0:9091"

include: []

plugins:
  # 直连域名
  - tag: direct_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/direct-list.txt"

  # 国外域名
  - tag: proxy_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/proxy-list.txt"

  # 广告域名
  - tag: reject_domain
    type: domain_set
    args:
      files:
        - "/var/mosdns/reject-list.txt"

  # 白名单域名
  - tag: white_domain
    type: domain_set
    args:
      exps:
        - "domain:pt"

        # 金融和区块链
        - "domain:paypal.com"
        - "domain:coingecko.com"
        - "domain:gateio.ws"
        - "domain:getgrass.io"
        - "domain:wynd.network"
        - "domain:fluence.network"
        - "domain:binance.com"

        # 科技公司域名
        - "domain:zeabur.com"
        - "domain:anaconda.org"
        - "domain:jsdelivr.net"
        - "domain:icloud.com"
        - "domain:tailscale.com"
        - "domain:tailscale.io"
        - "domain:cloudflare.com"
        - "domain:auth0.com"
        - "domain:apple.com"
        - "domain:windows.com"
        - "domain:microsoft.com"
        - "domain:cloudflarestorage.com"

        # 网络服务域名
        - "domain:lscr.io"
        - "domain:hf-mirror.com"
        - "domain:letsencrypt.org"
        - "domain:test-ipv6.com"
        - "domain:ooo.cool"
        - "domain:turboai.io"
        - "domain:cursor.sh"
        - "domain:cursor.com"
        - "domain:maptiler.com"
        - "domain:claw.cloud"

  # 动态域名
  - tag: dynamic_domain
    type: domain_set
    args:
      exps:
        - "domain:bone6.top"
        - "domain:bone6.com"
        - "domain:grifcc.top"

  # 直连 IP
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/cn.txt"

  # 转发至 SmartDNS
  - tag: forward_domestic
    type: forward
    args:
      upstreams:
        - addr: 127.0.0.1:6153

  # 转发至 Mihomo 获取 FakeIP 
  - tag: forward_overseas
    type: forward
    args:
      upstreams:
        - addr: 127.0.0.1:7874

  # 转发至 Cloudflare（个人域名运营商）
  - tag: forward_personal
    type: forward
    args:
      upstreams:
        - addr: 1.0.0.1

  # 国内解析
  - tag: domestic_sequence
    type: sequence
    args:
      - exec: $forward_domestic

  # 国外解析
  - tag: overseas_sequence_primary
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_overseas

  # 优先国外解析
  - tag: overseas_sequence
    type: fallback
    args:
      primary: overseas_sequence_primary
      secondary: domestic_sequence
      threshold: 500
      
  # 动态域名解析
  - tag: dynamic_sequence
    type: sequence
    args:
      - exec: $forward_personal

  # 有响应终止返回
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept

  # fallback 用本地服务器 sequence
  # 返回非国内 ip 则 drop_resp
  - tag: query_is_domestic_ip
    type: sequence
    args:
      - exec: $domestic_sequence
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp

  # fallback 用远程服务器 sequence
  - tag: query_is_overseas
    type: sequence
    args:
      - exec: $overseas_sequence

  # fallback 用本地服务器或远程服务器 sequence
  - tag: fallback
    type: fallback
    args:
      primary: query_is_domestic_ip
      secondary: query_is_overseas
      threshold: 500
      always_standby: true

  # 查询国内域名
  - tag: query_is_domestic_domain
    type: sequence
    args:
      - matches: qname $direct_domain
        exec: $domestic_sequence

  # 查询国外域名
  - tag: query_is_no_domestic_domain
    type: sequence
    args:
      - matches: qname $proxy_domain
        exec: $overseas_sequence

  # 查询动态域名
  - tag: query_is_dynamic_domain
    type: sequence
    args:
      - matches: qname $dynamic_domain 
        exec: $dynamic_sequence
      - matches: qname $white_domain 
        exec: $domestic_sequence

  # 查询广告域名
  - tag: query_is_ad_domain
    type: sequence
    args:
      - matches: qname $reject_domain
        exec: reject 3

  # 主要的运行逻辑插件
  - tag: main_sequence
    type: sequence
    args:
      - exec: $query_is_ad_domain

      - exec: $query_is_dynamic_domain
      - exec: jump has_resp_sequence
      
      - exec: $query_is_domestic_domain
      - exec: jump has_resp_sequence

      - exec: $query_is_no_domestic_domain
      - exec: jump has_resp_sequence

      - exec: $fallback

  # 启动 udp 服务器。
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"

  # 启动 tcp 服务器。
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
